# Logfile created on 2017-06-13 17:38:00 -0400 by logger.rb/44203
I, [2017-06-13T17:38:00.066947 #1589]  INFO -- : *** Below you'll find the most recent exception thrown, this will likely (but not certainly) be the exception that made your application exit abnormally ***
E, [2017-06-13T17:38:00.067017 #1589] ERROR -- : exit (SystemExit)
/Users/szagar/work/pyzts/daemons/ibgw2filed/lib/ib_gw_2file.rb:133:in `exit'
/Users/szagar/work/pyzts/daemons/ibgw2filed/lib/ib_gw_2file.rb:133:in `receive_data'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/eventmachine-1.0.4/lib/eventmachine.rb:187:in `run_machine'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/eventmachine-1.0.4/lib/eventmachine.rb:187:in `run'
/Users/szagar/work/pyzts/daemons/ibgw2filed/lib/ib_gw_2file.rb:215:in `block in initialize'
I, [2017-06-13T17:38:00.067094 #1589]  INFO -- : *** Below you'll find all the exception objects in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
E, [2017-06-13T17:38:00.067531 #1589] ERROR -- : stream closed (IOError)

E, [2017-06-13T17:38:00.067833 #1589] ERROR -- : failed to allocate memory (NoMemoryError)

E, [2017-06-13T17:38:00.067987 #1589] ERROR -- : stack level too deep (SystemStackError)

E, [2017-06-13T17:38:00.068359 #1589] ERROR -- : exception reentered (fatal)

E, [2017-06-13T17:38:00.078238 #1589] ERROR -- : Value will be available once the pipeline executes. (Redis::FutureNotReady)

E, [2017-06-13T17:38:00.080372 #1589] ERROR -- : No such file or directory @ rb_sysopen - /Users/szagar/work/pyzts/daemons/ibgw2filed/log/backtrace-20170613173800-1589.log (Errno::ENOENT)
/Users/szagar/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/logger.rb:592:in `initialize'
/Users/szagar/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/logger.rb:592:in `open'
/Users/szagar/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/logger.rb:592:in `open_logfile'
/Users/szagar/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/logger.rb:549:in `initialize'
/Users/szagar/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/logger.rb:318:in `new'
/Users/szagar/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/logger.rb:318:in `initialize'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/safely-0.3.2/lib/safely/backtrace.rb:24:in `new'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/safely-0.3.2/lib/safely/backtrace.rb:24:in `log_exceptions'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/safely-0.3.2/lib/safely/backtrace.rb:10:in `block in enable!'
E, [2017-06-13T17:38:00.080446 #1589] ERROR -- : exit (SystemExit)
/Users/szagar/work/pyzts/daemons/ibgw2filed/lib/ib_gw_2file.rb:133:in `exit'
/Users/szagar/work/pyzts/daemons/ibgw2filed/lib/ib_gw_2file.rb:133:in `receive_data'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/eventmachine-1.0.4/lib/eventmachine.rb:187:in `run_machine'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/eventmachine-1.0.4/lib/eventmachine.rb:187:in `run'
/Users/szagar/work/pyzts/daemons/ibgw2filed/lib/ib_gw_2file.rb:215:in `block in initialize'
E, [2017-06-13T17:38:00.080612 #1589] ERROR -- : Resource temporarily unavailable - read would block (IO::EAGAINWaitReadable)
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis/connection/ruby.rb:49:in `read_nonblock'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis/connection/ruby.rb:49:in `_read_from_socket'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis/connection/ruby.rb:41:in `gets'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis/connection/ruby.rb:273:in `read'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis/client.rb:245:in `block in read'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis/client.rb:233:in `io'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis/client.rb:244:in `read'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis/client.rb:109:in `block in call'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis/client.rb:214:in `block (2 levels) in process'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis/client.rb:340:in `ensure_connected'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis/client.rb:204:in `block in process'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis/client.rb:286:in `logging'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis/client.rb:203:in `process'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis/client.rb:109:in `call'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis.rb:784:in `block in get'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis.rb:37:in `block in synchronize'
/Users/szagar/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis.rb:37:in `synchronize'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis.rb:783:in `get'
/Users/szagar/work/pyzts/daemons/ibgw2filed/lib/redis_factory.rb:88:in `method_missing'
/Users/szagar/work/pyzts/daemons/ibgw2filed/lib/s_m.rb:47:in `tkr_lookup'
/Users/szagar/work/pyzts/daemons/ibgw2filed/lib/ib_gw_2file.rb:1131:in `subscribe_ticks'
/Users/szagar/work/pyzts/daemons/ibgw2filed/libexec/ibgwd-daemon.rb:38:in `block (2 levels) in start_broker'
/Users/szagar/work/pyzts/daemons/ibgw2filed/libexec/ibgwd-daemon.rb:38:in `each'
/Users/szagar/work/pyzts/daemons/ibgw2filed/libexec/ibgwd-daemon.rb:38:in `block in start_broker'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/eventmachine-1.0.4/lib/eventmachine.rb:968:in `call'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/eventmachine-1.0.4/lib/eventmachine.rb:968:in `block in run_deferred_callbacks'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/eventmachine-1.0.4/lib/eventmachine.rb:965:in `times'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/eventmachine-1.0.4/lib/eventmachine.rb:965:in `run_deferred_callbacks'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/eventmachine-1.0.4/lib/eventmachine.rb:187:in `run_machine'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/eventmachine-1.0.4/lib/eventmachine.rb:187:in `run'
/Users/szagar/work/pyzts/daemons/ibgw2filed/lib/ib_gw_2file.rb:215:in `block in initialize'
E, [2017-06-13T17:38:00.080718 #1589] ERROR -- : Socket is already connected - connect(2) for 127.0.0.1:6379 (Errno::EISCONN)
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis/connection/ruby.rb:129:in `connect_nonblock'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis/connection/ruby.rb:129:in `rescue in connect_addrinfo'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis/connection/ruby.rb:121:in `connect_addrinfo'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis/connection/ruby.rb:162:in `block in connect'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis/connection/ruby.rb:160:in `each'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis/connection/ruby.rb:160:in `each_with_index'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis/connection/ruby.rb:160:in `connect'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis/connection/ruby.rb:211:in `connect'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis/client.rb:316:in `establish_connection'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis/client.rb:91:in `block in connect'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis/client.rb:273:in `with_reconnect'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis/client.rb:90:in `connect'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis/client.rb:337:in `ensure_connected'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis/client.rb:204:in `block in process'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis/client.rb:286:in `logging'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis/client.rb:203:in `process'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis/client.rb:109:in `call'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis.rb:784:in `block in get'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis.rb:37:in `block in synchronize'
/Users/szagar/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis.rb:37:in `synchronize'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis.rb:783:in `get'
/Users/szagar/work/pyzts/daemons/ibgw2filed/lib/redis_factory.rb:88:in `method_missing'
/Users/szagar/work/pyzts/daemons/ibgw2filed/lib/s_m.rb:47:in `tkr_lookup'
/Users/szagar/work/pyzts/daemons/ibgw2filed/lib/ib_gw_2file.rb:1131:in `subscribe_ticks'
/Users/szagar/work/pyzts/daemons/ibgw2filed/libexec/ibgwd-daemon.rb:38:in `block (2 levels) in start_broker'
/Users/szagar/work/pyzts/daemons/ibgw2filed/libexec/ibgwd-daemon.rb:38:in `each'
/Users/szagar/work/pyzts/daemons/ibgw2filed/libexec/ibgwd-daemon.rb:38:in `block in start_broker'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/eventmachine-1.0.4/lib/eventmachine.rb:968:in `call'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/eventmachine-1.0.4/lib/eventmachine.rb:968:in `block in run_deferred_callbacks'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/eventmachine-1.0.4/lib/eventmachine.rb:965:in `times'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/eventmachine-1.0.4/lib/eventmachine.rb:965:in `run_deferred_callbacks'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/eventmachine-1.0.4/lib/eventmachine.rb:187:in `run_machine'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/eventmachine-1.0.4/lib/eventmachine.rb:187:in `run'
/Users/szagar/work/pyzts/daemons/ibgw2filed/lib/ib_gw_2file.rb:215:in `block in initialize'
E, [2017-06-13T17:38:00.080823 #1589] ERROR -- : Operation now in progress - connect(2) would block (IO::EINPROGRESSWaitWritable)
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis/connection/ruby.rb:122:in `connect_nonblock'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis/connection/ruby.rb:122:in `connect_addrinfo'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis/connection/ruby.rb:162:in `block in connect'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis/connection/ruby.rb:160:in `each'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis/connection/ruby.rb:160:in `each_with_index'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis/connection/ruby.rb:160:in `connect'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis/connection/ruby.rb:211:in `connect'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis/client.rb:316:in `establish_connection'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis/client.rb:91:in `block in connect'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis/client.rb:273:in `with_reconnect'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis/client.rb:90:in `connect'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis/client.rb:337:in `ensure_connected'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis/client.rb:204:in `block in process'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis/client.rb:286:in `logging'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis/client.rb:203:in `process'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis/client.rb:109:in `call'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis.rb:784:in `block in get'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis.rb:37:in `block in synchronize'
/Users/szagar/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis.rb:37:in `synchronize'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/redis-3.2.0/lib/redis.rb:783:in `get'
/Users/szagar/work/pyzts/daemons/ibgw2filed/lib/redis_factory.rb:88:in `method_missing'
/Users/szagar/work/pyzts/daemons/ibgw2filed/lib/s_m.rb:47:in `tkr_lookup'
/Users/szagar/work/pyzts/daemons/ibgw2filed/lib/ib_gw_2file.rb:1131:in `subscribe_ticks'
/Users/szagar/work/pyzts/daemons/ibgw2filed/libexec/ibgwd-daemon.rb:38:in `block (2 levels) in start_broker'
/Users/szagar/work/pyzts/daemons/ibgw2filed/libexec/ibgwd-daemon.rb:38:in `each'
/Users/szagar/work/pyzts/daemons/ibgw2filed/libexec/ibgwd-daemon.rb:38:in `block in start_broker'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/eventmachine-1.0.4/lib/eventmachine.rb:968:in `call'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/eventmachine-1.0.4/lib/eventmachine.rb:968:in `block in run_deferred_callbacks'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/eventmachine-1.0.4/lib/eventmachine.rb:965:in `times'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/eventmachine-1.0.4/lib/eventmachine.rb:965:in `run_deferred_callbacks'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/eventmachine-1.0.4/lib/eventmachine.rb:187:in `run_machine'
/Users/szagar/.rvm/gems/ruby-2.1.1@zts/gems/eventmachine-1.0.4/lib/eventmachine.rb:187:in `run'
/Users/szagar/work/pyzts/daemons/ibgw2filed/lib/ib_gw_2file.rb:215:in `block in initialize'
